# Generated by Django 6.0.5 on 2026-05-15 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="GitHub repository URL", unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Derived repo name (e.g. 'fastapi')", max_length=255
                    ),
                ),
                ("local_path", models.CharField(blank=True, max_length=1024)),
                ("default_branch", models.CharField(blank=True, max_length=255)),
                ("last_commit_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cloned", "Cloned"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "repositories",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="The user's research question"),
                ),
                (
                    "answer",
                    models.TextField(blank=True, help_text="Final agent answer"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("source_references", models.JSONField(blank=True, default=list)),
                ("total_tool_calls", models.PositiveIntegerField(default=0)),
                ("total_findings", models.PositiveIntegerField(default=0)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="app.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="File path the finding relates to",
                        max_length=1024,
                    ),
                ),
                (
                    "note",
                    models.TextField(help_text="The agent's observation or conclusion"),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("observation", "Observation"),
                            ("pattern", "Pattern"),
                            ("issue", "Issue"),
                            ("dependency", "Dependency"),
                            ("architecture", "Architecture"),
                        ],
                        default="observation",
                        max_length=32,
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(
                        help_text="The tool-call step at which this finding was recorded"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="app.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="ToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=64)),
                (
                    "tool_input",
                    models.JSONField(
                        default=dict, help_text="Arguments passed to the tool"
                    ),
                ),
                (
                    "tool_output",
                    models.TextField(
                        blank=True, help_text="Tool result (truncated to 10KB)"
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(help_text="Order within the session"),
                ),
                ("duration_ms", models.FloatField(blank=True, null=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="app.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
    ]
